version: "3.8"

services:
  db:
    image: mysql:8
    container_name: erb-mysql
    restart: always
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASS}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --ssl-mode=DISABLED

  api:
    build: .
    container_name: erb-api
    restart: always
    env_file: .env
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASS}
    ports:
      - "8754:8754"
    depends_on:
      - db

volumes:
  db_data:
