version: "3.8"

services:
  db:
    image: mysql:8.4
    container_name: erb-mysql
    restart: always
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_SSL_DISABLED: "true"
    command: --require_secure_transport=OFF
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
  
  redis:
    image: redis:7
    container_name: erb-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  api:
    build: .
    container_name: erb-api
    restart: always
    env_file: .env
    environment:
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASS}
      PORT: 8754
    ports:
      - "8754:8754"
    depends_on:
      - db
      - redis

  prometheus:
    image: prom/prometheus:latest
    container_name: erb-prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.enable-lifecycle"
    depends_on:
      - api

  grafana:
    image: grafana/grafana:latest
    container_name: erb-grafana
    restart: always
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  db_data:
  redis_data:
  prometheus_data:
  grafana_data: