version: "3"
services:
  authentication_service:
    image: nginx
    container_name: authentication_service
    volumes:
      - './nginx/default.conf:/etc/nginx/nginx.conf'
    ports:
      - '9119:80'
  app2:
    container_name: app2
    build:
      context: .
      dockerfile: Dockerfile 
    ports:
      - '8750:80'
    environment:
      - APPID=8750
