export const engineers = [
{ "type": "registered","reg_no":1916, "name":"Seku Kidemuka Peter","gender": "M", "field":"Civil", "reg_date":"Feb/20/2025" },
{ "type": "registered","reg_no":1917, "name":"Namungo Mark Rena","gender": "M", "field":"Electrical", "reg_date":"Feb/20/2025" },
{ "type": "registered","reg_no":1918, "name":"Ssemwanga Anthony","gender": "M", "field":"Electrical", "reg_date":"Feb/20/2025" },
{ "type": "registered","reg_no":1919, "name":"Bishop Samuel","gender": "M", "field":"Electrical", "reg_date":"Feb/20/2025" },
{ "type": "registered","reg_no":1920, "name":"Kitumba Aloysious","gender": "M", "field":"Electrical", "reg_date":"Feb/20/2025" },
{ "type": "registered","reg_no":1921, "name":"Ndyamuhaki Benon Banegura","gender": "M", "field":"Mechanical", "reg_date":"Feb/20/2025" },
{ "type": "registered","reg_no":1922, "name":"Shuwu Michael Peter ","gender": "M", "field":"Agricultural", "reg_date":"Feb/20/2025" },
{ "type": "registered","reg_no":1923, "name":"Akovuku Albert","gender": "M", "field":"Mechanical", "reg_date":"Feb/21/2025" },
{ "type": "registered","reg_no":1924, "name":"Mugambe David Oscar","gender": "M", "field":"Telecommunication", "reg_date":"Feb/21/2025" },
{ "type": "registered","reg_no": 1925, "name":"Nabwire Mwebaza Flavia","gender": "F", "field":"Electrical", "reg_date":"Feb/21/2025" },
{ "type": "registered","reg_no":1926, "name":"Waiswa Faizal","gender": "M", "field":"Civil", "reg_date":"Feb/21/2025" },
{ "type": "registered","reg_no":1927, "name":"Arinaitwe Joseph","gender": "M", "field":"Civil", "reg_date":"Feb/24/2025" },
{ "type": "registered","reg_no":1928, "name":"Ruzindana Bright Dancun","gender": "M", "field":"Civil", "reg_date":"Mar/20/2025" },
{ "type": "registered","reg_no":1929, "name":"Kyobe Jude Tadieus","gender": "M", "field":"Civil", "reg_date":"Mar/20/2025" },
{ "type": "registered","reg_no":1930, "name":"Balikowa Stephen","gender": "M", "field":"Electrical", "reg_date":"Mar/20/2025" },
{ "type": "registered","reg_no":1931, "name":"Zimbe Pafula Bigambo","gender": "M", "field":"Civil", "reg_date":"Mar/20/2025" },
{ "type": "registered","reg_no":1932, "name":"Ntende Moses Joseph","gender": "M", "field":"Mechanical", "reg_date":"Mar/20/2025" },
{ "type": "registered","reg_no":1933, "name":"Nsamba Muwonge Hamudan","gender": "M", "field":"Electrical", "reg_date":"Mar/21/2025" },
{ "type": "registered","reg_no":1934, "name":"Kitaka Michael","gender": "M", "field":"Civil", "reg_date":"Mar/21/2025" },
{ "type": "registered","reg_no":1935, "name":"Musiinguzi Daniel","gender": "M", "field":"Electrical", "reg_date":"Mar/21/2025" },
{ "type": "registered","reg_no":1936, "name":"Karamira James","gender": "M", "field":"Civil", "reg_date":"Mar/21/2025" },
{ "type": "registered","reg_no":1937, "name":"Kizito Bruce","gender": "M", "field":"Electrical", "reg_date":"Mar/21/2025" },
{ "type": "registered","reg_no":1938, "name":"Kyalimpa Brian Kisembo ","gender": "M", "field":"Civil", "reg_date":"Mar/21/2025" },
{ "type": "registered","reg_no":1939, "name":"Mugisha Dominic Mark","gender": "M", "field":"Electrical", "reg_date":"Mar/21/2025" },
{ "type": "registered","reg_no":1940, "name":"Wambete Job","gender": "M", "field":"Electrical", "reg_date":"Mar/24/2025" },
{ "type": "registered","reg_no":1941, "name":"Dr. Kangwagye Samuel","gender": "M", "field":"Mechanical", "reg_date":"Mar/24/2025" },
{ "type": "registered","reg_no":1942, "name":"Ssendagire John Paul","gender": "M", "field":"Electrical", "reg_date":"Mar/24/2025" },
{ "type": "registered","reg_no":1943, "name":"Kwikiriza Derrick","gender": "M", "field":"Civil", "reg_date":"Mar/24/2025" },
{ "type": "registered","reg_no":1944, "name":"Oketch Innocent","gender": "M", "field":"Electrical", "reg_date":"Mar/25/2025" },
{ "type": "registered","reg_no":1945, "name":"Mutyaba George William","gender": "M", "field":"Electrical", "reg_date":"Mar/25/2025" },
{ "type": "registered","reg_no":1946, "name":"Jjuuko Elias Yasin","gender": "M", "field":"Civil", "reg_date":"Mar/25/2025" },
{ "type": "registered","reg_no":1947, "name":"Dr. Okurut Kenan","gender": "M", "field":"Civil", "reg_date":"Mar/27/2025" },
{ "type": "registered","reg_no":1948, "name":"Tukamwakira Godfrey","gender": "M", "field":"Civil", "reg_date":" Apr/11/2025" },
{ "type": "registered","reg_no":1949, "name":"Agi Omagor Brian","gender": "M", "field":"Civil", "reg_date":" Apr/24/2025" },
{ "type": "registered","reg_no":1950, "name":"Byamukama Richard","gender": "M", "field":"Civil", "reg_date":" Apr/24/2025" },
{ "type": "registered","reg_no":1951, "name":"Mwije Philemon","gender": "M", "field":"Civil", "reg_date":" Apr/24/2025" },
{ "type": "registered","reg_no":1952, "name":"Lutaaya Ronald","gender": "M", "field":"Electronic", "reg_date":" Apr/24/2025" },
{ "type": "registered","reg_no":1953, "name":"Harera James Byaruhanga","gender": "M", "field":"Petroleum", "reg_date":" Apr/24/2025" },
{ "type": "registered","reg_no":1954, "name":"Ssekabemba Umaru","gender": "M", "field":"Automotive & Power", "reg_date":" Apr/24/2025" },
{ "type": "registered","reg_no":1955, "name":"Rwabwogo Joselynne Rwakakooko","gender": "F", "field":"Electrical", "reg_date":" Apr/24/2025" },
{ "type": "registered","reg_no":1956, "name":"Kusemererwa Charles","gender": "M", "field":"Civil", "reg_date":" Apr/24/2025" },
{ "type": "registered","reg_no":1957, "name":"Kanyerezi Nicholas","gender": "M", "field":"Electrical", "reg_date":" Apr/24/2025" },
{ "type": "registered","reg_no":1958, "name":"Mugoya Peterson","gender": "M", "field":"Civil", "reg_date":" Apr/24/2025" },
{ "type": "registered","reg_no":1959, "name":"Bukenya Ismail","gender": "M", "field":"Civil", "reg_date":" Apr/24/2025" },
{ "type": "registered","reg_no":1960, "name":"Tenywa Emmanuel ","gender": "M", "field":"Civil", "reg_date":" Apr/24/2025" },
{ "type": "registered","reg_no":1961, "name":"Dr. Tumwesigye Emmanuel","gender": "M", "field":"Civil", "reg_date":" Apr/24/2025" },
{ "type": "registered","reg_no":1962, "name":"Arishaba Aggrey","gender": "M", "field":"Automotive & Power", "reg_date":" Apr/24/2025" },
{ "type": "registered","reg_no":1963, "name":"Nanyunja Habiba Sulaiman","gender": "F", "field":"Civil", "reg_date":" Apr/24/2025" },
{ "type": "registered","reg_no":1964, "name":"Kabuye Enos","gender": "M", "field":"Electrical", "reg_date":" Apr/25/2025" },
{ "type": "registered","reg_no":1965, "name":"Kasumba Denis","gender": "M", "field":"Civil", "reg_date":" Apr/25/2025" },
{ "type": "registered","reg_no":1966, "name":"Wamboga Abraham","gender": "M", "field":"Civil", "reg_date":" Apr/25/2025" },
{ "type": "registered","reg_no":1967, "name":"Ssemugga John Paul","gender": "M", "field":"Mechanical", "reg_date":" Apr/25/2025" },
{ "type": "registered","reg_no":1968, "name":"Omoding Stephen","gender": "M", "field":"Civil", "reg_date":" Apr/28/2025" },
{ "type": "registered","reg_no":1969, "name":"Ssali Ismael","gender": "M", "field":"Mechanical", "reg_date":" Apr/28/2025" },
]