{
 "title": "ERB API Metrics",
 "tags": [
  "node",
  "api",
  "prometheus"
 ],
 "refresh": "5s",
 "panels": [
  {
   "title": "Total HTTP Requests",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 6, "h": 4 },
   "targets": [
    { "expr": "sum(http_requests_total)", "legendFormat": "Total Requests" }
   ]
  },
  {
   "title": "Requests per Route",
   "type": "graph",
   "gridPos": { "x": 6, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum by (route) (rate(http_requests_total[5sm]))",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "x": 0, "y": 8, "w": 9, "h": 8 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[1m])",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "x": 9, "y": 8, "w": 9, "h": 8 },
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "Memory" }
   ]
  }
 ]
}